default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: LightningTalkTopics_development

test:
  <<: *default
  database: LightningTalkTopics_test

# production:
#   <<: *default
#   database: LightningTalkTopics_production
#   username: LightningTalkTopics
#   password: <%= ENV['LIGHTNINGTALKTOPICS_DATABASE_PASSWORD'] %>
